name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
author:
  - Ahmed Shuaib <ahmed.shuaip600@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  equatable: ^2.0.0
  bloc: ^7.0.0-nullsafety.3
  # Functional programming thingies
  dartz: ^0.9.2
  form_bloc:
    path: ../plugins/form_bloc

dev_dependencies:
  bloc_test: ^8.0.0-nullsafety.1